//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovy
    {
        public long MovieID { get; set; }
        public string MovieName { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> Producer { get; set; }
        public string genre { get; set; }
        public string title { get; set; }
        public Nullable<long> review_by { get; set; }
        public string user_review { get; set; }
    
        public virtual tblProducer tblProducer { get; set; }
        public virtual User User { get; set; }
    }
}
