//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducer
    {
        public tblProducer()
        {
            this.tblMovies = new HashSet<tblMovy>();
        }
    
        public long ProducerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<long> NumberOfMovies { get; set; }
    
        public virtual ICollection<tblMovy> tblMovies { get; set; }
    }
}
